In [103]:
import pandas as pd
import numpy as np
import scipy

In [104]:
dtype_spec = {"sum": np.int64, "sum2": np.int64, "chi2cdf": np.float64, "parameters_ok": np.bool, "srcLittleEndian": np.bool, "dstLittleEndian": np.bool}
with open("../results.csv", "r") as f:
    df = pd.read_csv(f, sep="\s+", dtype=dtype_spec, keep_default_na=False)
df = df.drop(["hash","date","time","elapsed", "rng", "srcLittleEndian", "dstLittleEndian"], axis=1)
df

,offset,bitsPerSample,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
0,0,8,1,2,1,20,2,0,1,20,202,0.345279,True
1,0,16,1,2,1,20,2,0,1,20,202,0.345279,True
2,0,0,1,2,1,20,2,0,1,20,200,0.000000,True
3,0,8,1,2,1,40,2,0,1,40,808,0.472911,True
4,0,8,1,4,1,40,4,0,1,40,406,0.103568,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816,0,0,2,2048,2,83886080,4194304,0,1,83886080,1761571292,0.265102,True
1817,0,0,3,200,3,80000000,8000000,0,1,80000000,880010814,0.606710,True
1818,0,16,6,2,6,64000000,64,0,1,64000000,64000060346344,0.428512,True
1819,0,16,8,4,8,65536000,65536,0,1,65536000,65601372320,0.327121,True
1820,0,0,11,4,11,83886080,4194304,0,1,83886080,1761586162,0.355345,True

In [105]:
mask = (df.chi2cdf > 0.9999)
df2 = df[mask].copy()
#df2
df2.groupby(["dim", "bitsPerSample", "parameters_ok"]).count()

                                 offset   m  stride   N  Mtotal  curtask  \
dim bitsPerSample parameters_ok
1   8             False              27  27      27  27      27       27
    16            False               7   7       7   7       7        7
                  True                1   1       1   1       1        1
2   8             False               6   6       6   6       6        6

                                 Ntasks  sum  sum2  chi2cdf
dim bitsPerSample parameters_ok
1   8             False              27   27    27       27
    16            False               7    7     7        7
                  True                1    1     1        1
2   8             False               6    6     6        6

In [ ]:
mask = ((df.dim == 1) & (df.bitsPerSample == 16) & (df.chi2cdf > 0.9999) & (df.parameters_ok == True))
mask = np.flatnonzero(mask)
row = df.iloc[mask[0]]
#dof = row["Mtotal"]-1
#sum = row["sum"]
#mean = row["sum"]/(dof+1)
#sum2 = row["sum2"]
#chi2 = sum2/mean - sum
#chi2cdf = scipy.stats.chi2.cdf(chi2, dof)
row["chi2cdf"]

np.float64(2.0465407146730286e-11)

In [107]:
df.groupby(["dim", "bitsPerSample"]).count()

                   offset    m  stride    N  Mtotal  curtask  Ntasks  sum  \
dim bitsPerSample
1   0                 199  199     199  199     199      199     199  199
    8                 108  108     108  108     108      108     108  108
    16                172  172     172  172     172      172     172  172
2   0                 212  212     212  212     212      212     212  212
    8                  76   76      76   76      76       76      76   76
    16                180  180     180  180     180      180     180  180
3   0                 132  132     132  132     132      132     132  132
    8                  32   32      32   32      32       32      32   32
    16                112  112     112  112     112      112     112  112
4   0                  88   88      88   88      88       88      88   88
    8                  30   30      30   30      30       30      30   30
    16                 62   62      62   62      62       62      62   62
5   0                  56   56      56   56      56       56      56   56
    8                  16   16      16   16      16       16      16   16
    16                 38   38      38   38      38       38      38   38
6   0                  42   42      42   42      42       42      42   42
    8                  16   16      16   16      16       16      16   16
    16                 28   28      28   28      28       28      28   28
7   0                  28   28      28   28      28       28      28   28
    8                  14   14      14   14      14       14      14   14
    16                 24   24      24   24      24       24      24   24
8   0                  24   24      24   24      24       24      24   24
    8                  14   14      14   14      14       14      14   14
    16                 24   24      24   24      24       24      24   24
9   0                  22   22      22   22      22       22      22   22
    16                 14   14      14   14      14       14      14   14
10  0                  18   18      18   18      18       18      18   18
    16                 12   12      12   12      12       12      12   12
11  0                  16   16      16   16      16       16      16   16
    16                 12   12      12   12      12       12      12   12

                   sum2  chi2cdf  parameters_ok
dim bitsPerSample
1   0               199      199            199
    8               108      108            108
    16              172      172            172
2   0               212      212            212
    8                76       76             76
    16              180      180            180
3   0               132      132            132
    8                32       32             32
    16              112      112            112
4   0                88       88             88
    8                30       30             30
    16               62       62             62
5   0                56       56             56
    8                16       16             16
    16               38       38             38
6   0                42       42             42
    8                16       16             16
    16               28       28             28
7   0                28       28             28
    8                14       14             14
    16               24       24             24
8   0                24       24             24
    8                14       14             14
    16               24       24             24
9   0                22       22             22
    16               14       14             14
10  0                18       18             18
    16               12       12             12
11  0                16       16             16
    16               12       12             12

In [108]:
pivot = pd.pivot_table(df2, columns=["N"], index="dim", values="N")
pivot

ValueError: Grouper for 'N' not 1-dimensional