In [5]:
import pandas as pd
import numpy as np

In [ ]:
dtype_spec = {"sum": int, "sum2:", int, "chi2cdf": float}
with open("../results_corr.csv", "r") as f:
    df = pd.read_csv(f, sep=" ", dtype=dtype_spec, keep_default_na=False)
df.chi2cdf = df.chi2cdf.astype(float)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,hash,rng,offset,dim,m,N,Mtot,curtask,Ntasks,sum,sum2,chi2cdf
0,166a320f22d7c6b2,1,0,16,True,True,1,2,20,2,0,1,20,250,0.974653
1,10f5df379ce0ac39,1,0,16,True,True,1,2,40,2,0,1,40,850,0.886154
2,1fbd7d92281713ca,1,0,16,True,True,1,4,40,4,0,1,40,438,0.716114
3,072ce13c71ca6878,1,0,16,True,True,2,2,40,4,0,1,40,450,0.828203
4,073c5a4db752edfe,1,0,16,True,True,1,4,80,4,0,1,80,1666,0.652357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,27329242d53b509b,1,0,8,True,True,1,16777216,838860800,16777216,0,1,838860800,2748779907767238,1.000000
1212,34760d8ddbc483d0,1,0,8,True,True,8,4,655360000,65536,0,1,655360000,6554253900026,0.344962
1213,1bb7a613cc5016b8,1,0,8,True,True,5,32,671088640,33554432,0,1,671088640,14092855278,0.485080
1214,124cc7eb10d12fdc,1,0,8,True,True,8,8,838860800,16777216,0,1,838860800,42781902290,0.502167
1215,1577d8fb7b7c2967,1,0,8,True,True,2,4096,838860800,16777216,0,1,838860800,10738256001696,1.000000

In [27]:
mask = (df.chi2cdf > 1 - 1e-9)
df2 = df[mask]
df2['chi2cdf'] = df2['chi2cdf'] - 1
df2

/tmp/ipykernel_17679/3687342491.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['chi2cdf'] = df2['chi2cdf'] - 1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,hash,rng,offset,dim,m,N,Mtot,curtask,Ntasks,sum,sum2,chi2cdf
220,05882c25125b29cc,1,0,16,True,True,1,10000,200000,10000,0,1,200000,4223864,-2.220446e-16
257,4d443ef22fb1390e,1,0,16,True,True,1,10000,500000,10000,0,1,500000,25645006,0.000000e+00
288,010a02897c06eb7c,1,0,16,True,True,1,10000,1000000,10000,0,1,1000000,101574700,0.000000e+00
289,1286a8fa68be860d,1,0,16,True,True,1,100000,1000000,100000,0,1,1000000,16251106,0.000000e+00
302,17472a1f738d9489,1,0,16,True,True,1,131072,1310720,131072,0,1,1310720,27527074,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,12dafe024e042eee,1,0,8,True,True,1,8388608,838860800,8388608,0,1,838860800,2748779907767238,0.000000e+00
1205,1cd74a8191672baf,1,0,8,True,True,6,20,640000000,64000000,0,1,640000000,7077635230,0.000000e+00
1207,21413878771af395,1,0,8,True,True,2,8192,671088640,67108864,0,1,671088640,6872618182700,0.000000e+00
1211,27329242d53b509b,1,0,8,True,True,1,16777216,838860800,16777216,0,1,838860800,2748779907767238,0.000000e+00
1215,1577d8fb7b7c2967,1,0,8,True,True,2,4096,838860800,16777216,0,1,838860800,10738256001696,0.000000e+00