In [142]:
import pandas as pd
import numpy as np
import scipy

In [143]:
dtype_spec = {"sum": np.int64, "sum2": np.int64, "chi2cdf": np.float64, "parameters_ok": np.bool, "srcLittleEndian": np.bool, "dstLittleEndian": np.bool}
with open("../results.csv", "r") as f:
    df = pd.read_csv(f, sep="\s+", dtype=dtype_spec, keep_default_na=False)
df = df.drop(["hash","date","time","elapsed", "rng"], axis=1)
df
#df2 = df[(df.dim==1) & (df.m==2) & (df.stride==1) & (df.N==20)]
#df2

,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
0,0,0,True,True,1,2,1,20,2,0,1,20,200,0.000000,True
1,0,0,True,True,1,2,1,40,2,0,1,40,808,0.472911,True
2,0,0,True,True,1,4,1,40,4,0,1,40,406,0.103568,True
3,0,0,True,True,2,2,2,40,4,0,1,40,410,0.198748,True
4,0,0,True,True,2,2,1,40,4,0,1,40,412,0.246996,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21509,0,16,True,False,2,30,7,90000000,900,0,1,90000000,9000084669202,0.107014,True
21510,0,16,False,False,2,30,5,90000000,900,0,1,90000000,9000096196722,0.928852,True
21511,0,16,False,False,1,8192,7,81920000,8192,0,1,81920000,819283372852,0.873146,True
21512,0,16,False,False,2,30,6,90000000,900,0,1,90000000,9000089208444,0.441259,True
21513,0,16,False,False,2,30,7,90000000,900,0,1,90000000,9000091456546,0.648283,True

In [144]:
alpha = 1e-6
mask = (df.chi2cdf > 1-alpha) & (df.parameters_ok == True)
df2 = df[mask].copy()
#df2
df2.groupby(["dim", "bitsPerSample", "parameters_ok", "srcLittleEndian", "dstLittleEndian", "stride"]).count()

                                                                        offset  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   16            True          False           False           1            1
                                                                2            1
                                                                3            1
                                                                4            1
                                                                6            1
                                                                7            1
                                                True            2            1
                                                                3            1
                                                                5            1
                                                                7            1
                                True            False           2            1
                                                                3            1
                                                                4            1
                                                                6            1
                                                                7            1
                                                True            1            1
                                                                3            1
                                                                4            1
                                                                5            1
                                                                6            1
3   16            True          True            True            4            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1

                                                                        m  N  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   16            True          False           False           1       1  1
                                                                2       1  1
                                                                3       1  1
                                                                4       1  1
                                                                6       1  1
                                                                7       1  1
                                                True            2       1  1
                                                                3       1  1
                                                                5       1  1
                                                                7       1  1
                                True            False           2       1  1
                                                                3       1  1
                                                                4       1  1
                                                                6       1  1
                                                                7       1  1
                                                True            1       1  1
                                                                3       1  1
                                                                4       1  1
                                                                5       1  1
                                                                6       1  1
3   16            True          True            True            4       1  1
8   16            True          False           True            2       1  1
                                True            False           2       1  1
9   16            True          True            False           2       1  1

                                                                        Mtotal  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   16            True          False           False           1            1
                                                                2            1
                                                                3            1
                                                                4            1
                                                                6            1
                                                                7            1
                                                True            2            1
                                                                3            1
                                                                5            1
                                                                7            1
                                True            False           2            1
                                                                3            1
                                                                4            1
                                                                6            1
                                                                7            1
                                                True            1            1
                                                                3            1
                                                                4            1
                                                                5            1
                                                                6            1
3   16            True          True            True            4            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1

                                                                        curtask  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   16            True          False           False           1             1
                                                                2             1
                                                                3             1
                                                                4             1
                                                                6             1
                                                                7             1
                                                True            2             1
                                                                3             1
                                                                5             1
                                                                7             1
                                True            False           2             1
                                                                3             1
                                                                4             1
                                                                6             1
                                                                7             1
                                                True            1             1
                                                                3             1
                                                                4             1
                                                                5             1
                                                                6             1
3   16            True          True            True            4             1
8   16            True          False           True            2             1
                                True            False           2             1
9   16            True          True            False           2             1

                                                                        Ntasks  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   16            True          False           False           1            1
                                                                2            1
                                                                3            1
                                                                4            1
                                                                6            1
                                                                7            1
                                                True            2            1
                                                                3            1
                                                                5            1
                                                                7            1
                                True            False           2            1
                                                                3            1
                                                                4            1
                                                                6            1
                                                                7            1
                                                True            1            1
                                                                3            1
                                                                4            1
                                                                5            1
                                                                6            1
3   16            True          True            True            4            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1

                                                                        sum  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   16            True          False           False           1         1
                                                                2         1
                                                                3         1
                                                                4         1
                                                                6         1
                                                                7         1
                                                True            2         1
                                                                3         1
                                                                5         1
                                                                7         1
                                True            False           2         1
                                                                3         1
                                                                4         1
                                                                6         1
                                                                7         1
                                                True            1         1
                                                                3         1
                                                                4         1
                                                                5         1
                                                                6         1
3   16            True          True            True            4         1
8   16            True          False           True            2         1
                                True            False           2         1
9   16            True          True            False           2         1

                                                                        sum2  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   16            True          False           False           1          1
                                                                2          1
                                                                3          1
                                                                4          1
                                                                6          1
                                                                7          1
                                                True            2          1
                                                                3          1
                                                                5          1
                                                                7          1
                                True            False           2          1
                                                                3          1
                                                                4          1
                                                                6          1
                                                                7          1
                                                True            1          1
                                                                3          1
                                                                4          1
                                                                5          1
                                                                6          1
3   16            True          True            True            4          1
8   16            True          False           True            2          1
                                True            False           2          1
9   16            True          True            False           2          1

                                                                        chi2cdf
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   16            True          False           False           1             1
                                                                2             1
                                                                3             1
                                                                4             1
                                                                6             1
                                                                7             1
                                                True            2             1
                                                                3             1
                                                                5             1
                                                                7             1
                                True            False           2             1
                                                                3             1
                                                                4             1
                                                                6             1
                                                                7             1
                                                True            1             1
                                                                3             1
                                                                4             1
                                                                5             1
                                                                6             1
3   16            True          True            True            4             1
8   16            True          False           True            2             1
                                True            False           2             1
9   16            True          True            False           2             1

In [145]:
mask = (df.chi2cdf > 1 - alpha) & (df.parameters_ok == True)
mask = np.flatnonzero(mask)
for idx in mask:
    row = df.iloc[idx]
#dof = row["Mtotal"]-1
#sum = row["sum"]
#mean = row["sum"]/(dof+1)
#sum2 = row["sum2"]
#chi2 = sum2/mean - sum
#chi2cdf = scipy.stats.chi2.cdf(chi2, dof)
    print(f"idx = {idx}, chi2cdf = {row['chi2cdf']}")
df.iloc[mask]

idx = 4593, chi2cdf = 0.9999999999795346
idx = 4627, chi2cdf = 0.9999999999795346
idx = 11484, chi2cdf = 0.9999997852167596
idx = 11523, chi2cdf = 0.9999997852167596
idx = 11528, chi2cdf = 0.9999998190086824
idx = 18664, chi2cdf = 0.9999991447081206
idx = 20902, chi2cdf = 0.9999999989970232
idx = 20908, chi2cdf = 0.9999999999978216
idx = 20909, chi2cdf = 0.999999999532462
idx = 20918, chi2cdf = 0.9999999999999644
idx = 20926, chi2cdf = 0.9999999977854126
idx = 20931, chi2cdf = 0.9999999855413008
idx = 20932, chi2cdf = 0.9999999978820128
idx = 20933, chi2cdf = 0.9999999141724792
idx = 20934, chi2cdf = 0.9999999126914892
idx = 20945, chi2cdf = 0.9999999999909842
idx = 20949, chi2cdf = 0.999999999965475
idx = 20954, chi2cdf = 0.9999998781826372
idx = 20983, chi2cdf = 0.9999999999370838
idx = 20990, chi2cdf = 0.9999999999342748
idx = 21006, chi2cdf = 0.9999999941356996
idx = 21025, chi2cdf = 0.9999999999859182
idx = 21061, chi2cdf = 0.9999993956196096
idx = 21084, chi2cdf = 0.9999999996340546

,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
4593,0,16,True,True,1,500,1,50000000,500,0,1,50000000,5000073669404,1.000000,True
4627,0,16,False,False,1,500,1,50000000,500,0,1,50000000,5000073669404,1.000000,True
11484,0,16,False,True,8,2,2,25600,256,0,1,25600,2598596,1.000000,True
11523,0,16,True,False,8,2,2,25600,256,0,1,25600,2598596,1.000000,True
11528,0,16,True,False,9,2,2,25600,512,0,1,25600,1314528,1.000000,True
18664,0,16,True,True,3,4,4,6400000,64,0,1,6400000,640013193954,0.999999,True
20902,0,16,True,True,1,500,3,50000000,500,0,1,50000000,5000071234614,1.000000,True
20908,0,16,True,True,1,500,4,50000000,500,0,1,50000000,5000075000572,1.000000,True
20909,0,16,False,True,1,500,2,50000000,500,0,1,50000000,5000071725854,1.000000,True
20918,0,16,True,False,1,500,2,50000000,500,0,1,50000000,5000077334470,1.000000,True
20926,0,16,True,True,1,500,5,50000000,500,0,1,50000000,5000070716864,1.000000,True
20931,0,16,True,True,1,500,6,50000000,500,0,1,50000000,5000069455108,1.000000,True
20932,0,16,False,False,1,500,2,50000000,500,0,1,50000000,5000070746240,1.000000,True
20933,0,16,False,True,1,500,3,50000000,500,0,1,50000000,5000068205136,1.000000,True
20934,0,16,True,False,1,500,3,50000000,500,0,1,50000000,5000068192854,1.000000,True
20945,0,16,True,False,1,500,4,50000000,500,0,1,50000000,5000074161884,1.000000,True
20949,0,16,False,False,1,500,3,50000000,500,0,1,50000000,5000073351810,1.000000,True
20954,0,16,False,True,1,500,5,50000000,500,0,1,50000000,5000067952624,1.000000,True
20983,0,16,False,False,1,500,4,50000000,500,0,1,50000000,5000072983922,1.000000,True
20990,0,16,True,False,1,500,6,50000000,500,0,1,50000000,5000072957000,1.000000,True
21006,0,16,False,True,1,500,7,50000000,500,0,1,50000000,5000070068486,1.000000,True
21025,0,16,True,False,1,500,7,50000000,500,0,1,50000000,5000073894798,1.000000,True
21061,0,16,False,False,1,500,6,50000000,500,0,1,50000000,5000066765722,0.999999,True
21084,0,16,False,False,1,500,7,50000000,500,0,1,50000000,5000071882016,1.000000,True