In [36]:
import pandas as pd
import numpy as np
import scipy

In [48]:
dtype_spec = {"sum": np.int64, "sum2": np.int64, "chi2cdf": np.float64, "parameters_ok": np.bool, "srcLittleEndian": np.bool, "dstLittleEndian": np.bool}
with open("../results.csv", "r") as f:
    df = pd.read_csv(f, sep="\s+", dtype=dtype_spec, keep_default_na=False)
df = df.drop(["date","time","elapsed", "rng"], axis=1)

In [38]:
alpha = 1e-6
mask = (df.chi2cdf > 1-alpha) & (df.parameters_ok == True)
df2 = df[mask].copy()
df2.insert(10, 'n per cell', df2.N/df2.Mtotal)
#df2
df2.groupby(["dim", "bitsPerSample", "parameters_ok", "srcLittleEndian", "dstLittleEndian", "stride"]).count()

                                                                        hash  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4          1
8   16            True          False           True            2          1
                                True            False           2          1
9   16            True          True            False           2          1

                                                                        offset  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1

                                                                        m  N  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4       1  1
8   16            True          False           True            2       1  1
                                True            False           2       1  1
9   16            True          True            False           2       1  1

                                                                        Mtotal  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1

                                                                        n per cell  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4                1
8   16            True          False           True            2                1
                                True            False           2                1
9   16            True          True            False           2                1

                                                                        curtask  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4             1
8   16            True          False           True            2             1
                                True            False           2             1
9   16            True          True            False           2             1

                                                                        Ntasks  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1

                                                                        sum  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4         1
8   16            True          False           True            2         1
                                True            False           2         1
9   16            True          True            False           2         1

                                                                        sum2  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4          1
8   16            True          False           True            2          1
                                True            False           2          1
9   16            True          True            False           2          1

                                                                        chi2cdf
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4             1
8   16            True          False           True            2             1
                                True            False           2             1
9   16            True          True            False           2             1

In [39]:
df[(df.dim==1) & (df.m==4096) & (df.stride==0) & (df.bitsPerSample == 16) & (df.srcLittleEndian == False) & (df.dstLittleEndian == False)]
df[df.stride==0]

Empty DataFrame
Columns: [hash, offset, bitsPerSample, srcLittleEndian, dstLittleEndian, dim, m, stride, N, Mtotal, curtask, Ntasks, sum, sum2, chi2cdf, parameters_ok]
Index: []

In [40]:
df2.groupby(["sum2"]).count()

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,n per cell,curtask,Ntasks,sum,chi2cdf,parameters_ok
sum2,,,,,,,,,,,,,,,,
1314528,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2598596,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
640013193954,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [42]:
df2

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,n per cell,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
8511,01701bf8635b2095,0,16,False,True,8,2,2,25600,256,100.0,0,1,25600,2598596,1.000000,True
8564,708a5474d5bf9cf8,0,16,True,False,8,2,2,25600,256,100.0,0,1,25600,2598596,1.000000,True
8572,1f839344d1585d48,0,16,True,False,9,2,2,25600,512,50.0,0,1,25600,1314528,1.000000,True
17821,0d45f80a53c46f18,0,16,True,True,3,4,4,6400000,64,100000.0,0,1,6400000,640013193954,0.999999,True

In [43]:
mask = ((df.chi2cdf > 1 - alpha)) & (df.parameters_ok == True)
mask = np.flatnonzero(mask)
for idx in mask:
    row = df.iloc[idx]
#dof = row["Mtotal"]-1
#sum = row["sum"]
#mean = row["sum"]/(dof+1)
#sum2 = row["sum2"]
#chi2 = sum2/mean - sum
#chi2cdf = scipy.stats.chi2.cdf(chi2, dof)
    print(f"idx = {idx}, chi2cdf = {row['chi2cdf']}")
df.iloc[mask]

idx = 8511, chi2cdf = 0.9999997852167596
idx = 8564, chi2cdf = 0.9999997852167596
idx = 8572, chi2cdf = 0.9999998190086824
idx = 17821, chi2cdf = 0.9999991447081206

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
8511,01701bf8635b2095,0,16,False,True,8,2,2,25600,256,0,1,25600,2598596,1.000000,True
8564,708a5474d5bf9cf8,0,16,True,False,8,2,2,25600,256,0,1,25600,2598596,1.000000,True
8572,1f839344d1585d48,0,16,True,False,9,2,2,25600,512,0,1,25600,1314528,1.000000,True
17821,0d45f80a53c46f18,0,16,True,True,3,4,4,6400000,64,0,1,6400000,640013193954,0.999999,True