In [8]:
import pandas as pd
import numpy as np
import scipy

In [15]:
dtype_spec = {"sum": np.int64, "sum2": np.int64, "chi2cdf": np.float64, "parameters_ok": np.bool, "srcLittleEndian": np.bool, "dstLittleEndian": np.bool}
with open("../results.csv", "r") as f:
    df = pd.read_csv(f, sep="\s+", dtype=dtype_spec, keep_default_na=False)
df = df.drop(["date","time","elapsed", "rng"], axis=1)
df

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
0,2328d7d51b69aa46,0,8,False,False,1,2,1,20,2,0,1,20,202,0.345279,True
1,0bf5c7b73b605c41,0,8,False,False,1,2,2,20,2,0,1,20,202,0.345279,True
2,06c5f05cc73e5e3a,0,8,False,False,1,2,3,20,2,0,1,20,202,0.345279,True
3,1de1446a8bca2727,0,8,False,False,1,2,4,20,2,0,1,20,202,0.345279,True
4,4b5b77d57216a95a,0,8,False,False,1,2,5,20,2,0,1,20,232,0.926362,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41174,6ebfec1e1c29fe29,0,16,False,True,10,4,3,10485760000,1048576,0,1,10485760000,104906149758886,1.000000,True
41175,1dfeeb7ea85c6bb3,0,16,False,True,4,32,4,10485760000,1048576,0,1,10485760000,104953989323720,1.000000,True
41176,5b9cfee2f36f0a7f,0,16,False,True,4,32,5,10485760000,1048576,0,1,10485760000,104906145067100,1.000000,True
41177,125f279d1cd7dfd2,0,16,False,True,5,16,5,10485760000,1048576,0,1,10485760000,104906261654852,1.000000,True
41178,146979c52472f2a1,0,16,False,True,10,4,4,10485760000,1048576,0,1,10485760000,104954014341694,1.000000,True

In [10]:
alpha = 1e-6
mask = (df.chi2cdf > 1-alpha) & (df.parameters_ok == True)
df2 = df[mask].copy()
df2.insert(10, 'n per cell', df2.N/df2.Mtotal)
#df2
df2.groupby(["dim", "bitsPerSample", "parameters_ok", "srcLittleEndian", "dstLittleEndian", "stride"]).count()

                                                                        hash  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4          1
4   16            True          False           True            4          1
                                                                5          1
5   16            True          False           True            1          1
                                                                2          1
                                                                3          1
                                                                4          1
                                                                5          1
8   16            True          False           True            2          1
                                True            False           2          1
9   16            True          True            False           2          1
10  16            True          False           True            1          1
                                                                2          1
                                                                3          1
                                                                4          1

                                                                        offset  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4            1
4   16            True          False           True            4            1
                                                                5            1
5   16            True          False           True            1            1
                                                                2            1
                                                                3            1
                                                                4            1
                                                                5            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1
10  16            True          False           True            1            1
                                                                2            1
                                                                3            1
                                                                4            1

                                                                        m  N  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4       1  1
4   16            True          False           True            4       1  1
                                                                5       1  1
5   16            True          False           True            1       1  1
                                                                2       1  1
                                                                3       1  1
                                                                4       1  1
                                                                5       1  1
8   16            True          False           True            2       1  1
                                True            False           2       1  1
9   16            True          True            False           2       1  1
10  16            True          False           True            1       1  1
                                                                2       1  1
                                                                3       1  1
                                                                4       1  1

                                                                        Mtotal  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4            1
4   16            True          False           True            4            1
                                                                5            1
5   16            True          False           True            1            1
                                                                2            1
                                                                3            1
                                                                4            1
                                                                5            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1
10  16            True          False           True            1            1
                                                                2            1
                                                                3            1
                                                                4            1

                                                                        n per cell  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4                1
4   16            True          False           True            4                1
                                                                5                1
5   16            True          False           True            1                1
                                                                2                1
                                                                3                1
                                                                4                1
                                                                5                1
8   16            True          False           True            2                1
                                True            False           2                1
9   16            True          True            False           2                1
10  16            True          False           True            1                1
                                                                2                1
                                                                3                1
                                                                4                1

                                                                        curtask  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4             1
4   16            True          False           True            4             1
                                                                5             1
5   16            True          False           True            1             1
                                                                2             1
                                                                3             1
                                                                4             1
                                                                5             1
8   16            True          False           True            2             1
                                True            False           2             1
9   16            True          True            False           2             1
10  16            True          False           True            1             1
                                                                2             1
                                                                3             1
                                                                4             1

                                                                        Ntasks  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4            1
4   16            True          False           True            4            1
                                                                5            1
5   16            True          False           True            1            1
                                                                2            1
                                                                3            1
                                                                4            1
                                                                5            1
8   16            True          False           True            2            1
                                True            False           2            1
9   16            True          True            False           2            1
10  16            True          False           True            1            1
                                                                2            1
                                                                3            1
                                                                4            1

                                                                        sum  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4         1
4   16            True          False           True            4         1
                                                                5         1
5   16            True          False           True            1         1
                                                                2         1
                                                                3         1
                                                                4         1
                                                                5         1
8   16            True          False           True            2         1
                                True            False           2         1
9   16            True          True            False           2         1
10  16            True          False           True            1         1
                                                                2         1
                                                                3         1
                                                                4         1

                                                                        sum2  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4          1
4   16            True          False           True            4          1
                                                                5          1
5   16            True          False           True            1          1
                                                                2          1
                                                                3          1
                                                                4          1
                                                                5          1
8   16            True          False           True            2          1
                                True            False           2          1
9   16            True          True            False           2          1
10  16            True          False           True            1          1
                                                                2          1
                                                                3          1
                                                                4          1

                                                                        chi2cdf
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
3   16            True          True            True            4             1
4   16            True          False           True            4             1
                                                                5             1
5   16            True          False           True            1             1
                                                                2             1
                                                                3             1
                                                                4             1
                                                                5             1
8   16            True          False           True            2             1
                                True            False           2             1
9   16            True          True            False           2             1
10  16            True          False           True            1             1
                                                                2             1
                                                                3             1
                                                                4             1

In [11]:
df[(df.dim==1) & (df.m==4096) & (df.stride==0) & (df.bitsPerSample == 16) & (df.srcLittleEndian == False) & (df.dstLittleEndian == False)]
df[df.stride==0]

Empty DataFrame
Columns: [hash, offset, bitsPerSample, srcLittleEndian, dstLittleEndian, dim, m, stride, N, Mtotal, curtask, Ntasks, sum, sum2, chi2cdf, parameters_ok]
Index: []

In [12]:
df2.groupby(["sum2"]).count()

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,n per cell,curtask,Ntasks,sum,chi2cdf,parameters_ok
sum2,,,,,,,,,,,,,,,,
1314528,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2598596,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
640013193954,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104906145067100,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104906149758886,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104906243030688,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104906261654852,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104953715974440,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104953823514092,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104953826312732,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104953938604046,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104953989323720,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104954014341694,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104954218373246,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [13]:
df2

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,n per cell,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
8511,01701bf8635b2095,0,16,False,True,8,2,2,25600,256,100.0,0,1,25600,2598596,1.000000,True
8564,708a5474d5bf9cf8,0,16,True,False,8,2,2,25600,256,100.0,0,1,25600,2598596,1.000000,True
8572,1f839344d1585d48,0,16,True,False,9,2,2,25600,512,50.0,0,1,25600,1314528,1.000000,True
17821,0d45f80a53c46f18,0,16,True,True,3,4,4,6400000,64,100000.0,0,1,6400000,640013193954,0.999999,True
41168,3207842905a126a9,0,16,False,True,5,16,1,10485760000,1048576,10000.0,0,1,10485760000,104953938604046,1.000000,True
41169,1c98c9641b7cfd28,0,16,False,True,10,4,1,10485760000,1048576,10000.0,0,1,10485760000,104953826312732,1.000000,True
41170,1434482d8465f1f5,0,16,False,True,10,4,2,10485760000,1048576,10000.0,0,1,10485760000,104953823514092,1.000000,True
41171,67e20a6e6eb310cf,0,16,False,True,5,16,2,10485760000,1048576,10000.0,0,1,10485760000,104953715974440,1.000000,True
41172,5e8a0fa67b65491e,0,16,False,True,5,16,3,10485760000,1048576,10000.0,0,1,10485760000,104906243030688,1.000000,True
41173,601921a1c3559608,0,16,False,True,5,16,4,10485760000,1048576,10000.0,0,1,10485760000,104954218373246,1.000000,True
41174,6ebfec1e1c29fe29,0,16,False,True,10,4,3,10485760000,1048576,10000.0,0,1,10485760000,104906149758886,1.000000,True
41175,1dfeeb7ea85c6bb3,0,16,False,True,4,32,4,10485760000,1048576,10000.0,0,1,10485760000,104953989323720,1.000000,True
41176,5b9cfee2f36f0a7f,0,16,False,True,4,32,5,10485760000,1048576,10000.0,0,1,10485760000,104906145067100,1.000000,True
41177,125f279d1cd7dfd2,0,16,False,True,5,16,5,10485760000,1048576,10000.0,0,1,10485760000,104906261654852,1.000000,True
41178,146979c52472f2a1,0,16,False,True,10,4,4,10485760000,1048576,10000.0,0,1,10485760000,104954014341694,1.000000,True

In [14]:
mask = ((df.chi2cdf > 1 - alpha)) & (df.parameters_ok == True)
mask = np.flatnonzero(mask)
for idx in mask:
    row = df.iloc[idx]
#dof = row["Mtotal"]-1
#sum = row["sum"]
#mean = row["sum"]/(dof+1)
#sum2 = row["sum2"]
#chi2 = sum2/mean - sum
#chi2cdf = scipy.stats.chi2.cdf(chi2, dof)
    print(f"idx = {idx}, chi2cdf = {row['chi2cdf']}")
df.iloc[mask]

idx = 8511, chi2cdf = 0.9999997852167596
idx = 8564, chi2cdf = 0.9999997852167596
idx = 8572, chi2cdf = 0.9999998190086824
idx = 17821, chi2cdf = 0.9999991447081206
idx = 41168, chi2cdf = 1.0
idx = 41169, chi2cdf = 1.0
idx = 41170, chi2cdf = 1.0
idx = 41171, chi2cdf = 1.0
idx = 41172, chi2cdf = 1.0
idx = 41173, chi2cdf = 1.0
idx = 41174, chi2cdf = 1.0
idx = 41175, chi2cdf = 1.0
idx = 41176, chi2cdf = 1.0
idx = 41177, chi2cdf = 1.0
idx = 41178, chi2cdf = 1.0

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
8511,01701bf8635b2095,0,16,False,True,8,2,2,25600,256,0,1,25600,2598596,1.000000,True
8564,708a5474d5bf9cf8,0,16,True,False,8,2,2,25600,256,0,1,25600,2598596,1.000000,True
8572,1f839344d1585d48,0,16,True,False,9,2,2,25600,512,0,1,25600,1314528,1.000000,True
17821,0d45f80a53c46f18,0,16,True,True,3,4,4,6400000,64,0,1,6400000,640013193954,0.999999,True
41168,3207842905a126a9,0,16,False,True,5,16,1,10485760000,1048576,0,1,10485760000,104953938604046,1.000000,True
41169,1c98c9641b7cfd28,0,16,False,True,10,4,1,10485760000,1048576,0,1,10485760000,104953826312732,1.000000,True
41170,1434482d8465f1f5,0,16,False,True,10,4,2,10485760000,1048576,0,1,10485760000,104953823514092,1.000000,True
41171,67e20a6e6eb310cf,0,16,False,True,5,16,2,10485760000,1048576,0,1,10485760000,104953715974440,1.000000,True
41172,5e8a0fa67b65491e,0,16,False,True,5,16,3,10485760000,1048576,0,1,10485760000,104906243030688,1.000000,True
41173,601921a1c3559608,0,16,False,True,5,16,4,10485760000,1048576,0,1,10485760000,104954218373246,1.000000,True
41174,6ebfec1e1c29fe29,0,16,False,True,10,4,3,10485760000,1048576,0,1,10485760000,104906149758886,1.000000,True
41175,1dfeeb7ea85c6bb3,0,16,False,True,4,32,4,10485760000,1048576,0,1,10485760000,104953989323720,1.000000,True
41176,5b9cfee2f36f0a7f,0,16,False,True,4,32,5,10485760000,1048576,0,1,10485760000,104906145067100,1.000000,True
41177,125f279d1cd7dfd2,0,16,False,True,5,16,5,10485760000,1048576,0,1,10485760000,104906261654852,1.000000,True
41178,146979c52472f2a1,0,16,False,True,10,4,4,10485760000,1048576,0,1,10485760000,104954014341694,1.000000,True