In [15]:
import pandas as pd
import numpy as np
import scipy

In [16]:
dtype_spec = {"sum": np.int64, "sum2": np.int64, "chi2cdf": np.float64, "parameters_ok": np.bool, "srcLittleEndian": np.bool, "dstLittleEndian": np.bool}
with open("../results.csv", "r") as f:
    df = pd.read_csv(f, sep="\s+", dtype=dtype_spec, keep_default_na=False)
df = df.drop(["date","time","elapsed", "rng"], axis=1)
df
#df2 = df[(df.dim==1) & (df.m==2) & (df.stride==1) & (df.N==20)]
#df2

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
0,2328d7d51b69aa46,0,8,False,False,1,2,1,20,2,0,1,20,202,0.345279,True
1,0bf5c7b73b605c41,0,8,False,False,1,2,2,20,2,0,1,20,202,0.345279,True
2,06c5f05cc73e5e3a,0,8,False,False,1,2,3,20,2,0,1,20,202,0.345279,True
3,1de1446a8bca2727,0,8,False,False,1,2,4,20,2,0,1,20,202,0.345279,True
4,4b5b77d57216a95a,0,8,False,False,1,2,5,20,2,0,1,20,232,0.926362,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38000,0719e3bb1fe376b6,0,0,True,True,1,8388608,9,83886080000,8388608,0,1,83886080000,838944679198024,0.433443,True
38001,7f8e696b7fa6fcc5,0,0,True,True,6,40,7,81920000000,4096000000,0,1,81920000000,1720320539390,0.617241,True
38002,0d18cf00e4d1e84e,0,0,True,True,6,40,6,81920000000,4096000000,0,1,81920000000,1720320755744,0.661939,True
38003,010598de2a052851,0,0,True,True,6,40,1,81920000000,4096000000,0,1,81920000000,1720319137538,0.316973,True
38004,678485c73f02de6a,0,0,True,True,6,40,5,81920000000,4096000000,0,1,81920000000,1720321474230,0.792369,True

In [21]:
alpha = 1e-6
mask = (df.chi2cdf > 1-alpha) & (df.parameters_ok == True)
df2 = df[mask].copy()
df2.insert(10, 'n per cell', df2.N/df2.Mtotal)
#df2
df2.groupby(["dim", "bitsPerSample", "parameters_ok", "srcLittleEndian", "dstLittleEndian", "stride"]).count()

                                                                        hash  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0        295
    8             True          False           False           0         63
                                                True            0         63
                                True            False           0         63
                                                True            0         63
...                                                                      ...
11  0             True          True            True            0         14
    16            True          False           False           0          8
                                                True            0          8
                                True            False           0          8
                                                True            0          8

                                                                        offset  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0          295
    8             True          False           False           0           63
                                                True            0           63
                                True            False           0           63
                                                True            0           63
...                                                                        ...
11  0             True          True            True            0           14
    16            True          False           False           0            8
                                                True            0            8
                                True            False           0            8
                                                True            0            8

                                                                          m  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0       295
    8             True          False           False           0        63
                                                True            0        63
                                True            False           0        63
                                                True            0        63
...                                                                     ...
11  0             True          True            True            0        14
    16            True          False           False           0         8
                                                True            0         8
                                True            False           0         8
                                                True            0         8

                                                                          N  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0       295
    8             True          False           False           0        63
                                                True            0        63
                                True            False           0        63
                                                True            0        63
...                                                                     ...
11  0             True          True            True            0        14
    16            True          False           False           0         8
                                                True            0         8
                                True            False           0         8
                                                True            0         8

                                                                        Mtotal  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0          295
    8             True          False           False           0           63
                                                True            0           63
                                True            False           0           63
                                                True            0           63
...                                                                        ...
11  0             True          True            True            0           14
    16            True          False           False           0            8
                                                True            0            8
                                True            False           0            8
                                                True            0            8

                                                                        n per cell  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0              295
    8             True          False           False           0               63
                                                True            0               63
                                True            False           0               63
                                                True            0               63
...                                                                            ...
11  0             True          True            True            0               14
    16            True          False           False           0                8
                                                True            0                8
                                True            False           0                8
                                                True            0                8

                                                                        curtask  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0           295
    8             True          False           False           0            63
                                                True            0            63
                                True            False           0            63
                                                True            0            63
...                                                                         ...
11  0             True          True            True            0            14
    16            True          False           False           0             8
                                                True            0             8
                                True            False           0             8
                                                True            0             8

                                                                        Ntasks  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0          295
    8             True          False           False           0           63
                                                True            0           63
                                True            False           0           63
                                                True            0           63
...                                                                        ...
11  0             True          True            True            0           14
    16            True          False           False           0            8
                                                True            0            8
                                True            False           0            8
                                                True            0            8

                                                                        sum  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0       295
    8             True          False           False           0        63
                                                True            0        63
                                True            False           0        63
                                                True            0        63
...                                                                     ...
11  0             True          True            True            0        14
    16            True          False           False           0         8
                                                True            0         8
                                True            False           0         8
                                                True            0         8

                                                                        sum2  \
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0        295
    8             True          False           False           0         63
                                                True            0         63
                                True            False           0         63
                                                True            0         63
...                                                                      ...
11  0             True          True            True            0         14
    16            True          False           False           0          8
                                                True            0          8
                                True            False           0          8
                                                True            0          8

                                                                        chi2cdf
dim bitsPerSample parameters_ok srcLittleEndian dstLittleEndian stride
1   0             True          True            True            0           295
    8             True          False           False           0            63
                                                True            0            63
                                True            False           0            63
                                                True            0            63
...                                                                         ...
11  0             True          True            True            0            14
    16            True          False           False           0             8
                                                True            0             8
                                True            False           0             8
                                                True            0             8

[91 rows x 11 columns]

In [20]:
df2

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,n per cell,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
8511,01701bf8635b2095,0,16,False,True,8,2,2,25600,256,100.0,0,1,25600,2598596,1.000000,True
8564,708a5474d5bf9cf8,0,16,True,False,8,2,2,25600,256,100.0,0,1,25600,2598596,1.000000,True
8572,1f839344d1585d48,0,16,True,False,9,2,2,25600,512,50.0,0,1,25600,1314528,1.000000,True
17821,0d45f80a53c46f18,0,16,True,True,3,4,4,6400000,64,100000.0,0,1,6400000,640013193954,0.999999,True
23205,058cad01a53ca801,0,8,False,False,1,2,0,40,2,20.0,0,1,40,1600,1.000000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37926,699568eaf77c0227,0,0,True,True,6,30,0,72900000000,729000000,100.0,0,1,72900000000,1747706771649134592,1.000000,True
37935,1a40f73191b1b194,0,0,True,True,3,200,0,80000000000,8000000,10000.0,0,1,80000000000,17426550496495140864,1.000000,True
37946,0c65aef169d703b1,0,0,True,True,4,200,0,80000000000,1600000000,50.0,0,1,80000000000,17426550496495140864,1.000000,True
37952,78dd53d98f1bcf8a,0,0,True,True,4,30,0,81000000000,810000,100000.0,0,1,81000000000,12405853833109176320,1.000000,True
37973,44eb9a12378d04f5,0,0,True,True,1,8388608,0,83886080000,8388608,10000.0,0,1,83886080000,8664925683060834304,1.000000,True

In [19]:
mask = ((df.chi2cdf > 1 - alpha)) & (df.parameters_ok == True)
mask = np.flatnonzero(mask)
for idx in mask:
    row = df.iloc[idx]
#dof = row["Mtotal"]-1
#sum = row["sum"]
#mean = row["sum"]/(dof+1)
#sum2 = row["sum2"]
#chi2 = sum2/mean - sum
#chi2cdf = scipy.stats.chi2.cdf(chi2, dof)
    print(f"idx = {idx}, chi2cdf = {row['chi2cdf']}")
df.iloc[mask]

idx = 8511, chi2cdf = 0.9999997852167596
idx = 8564, chi2cdf = 0.9999997852167596
idx = 8572, chi2cdf = 0.9999998190086824
idx = 17821, chi2cdf = 0.9999991447081206
idx = 23205, chi2cdf = 0.9999999997460371
idx = 23206, chi2cdf = 1.0
idx = 23207, chi2cdf = 1.0
idx = 23208, chi2cdf = 0.9999999997460371
idx = 23209, chi2cdf = 1.0
idx = 23210, chi2cdf = 1.0
idx = 23211, chi2cdf = 0.9999999997460371
idx = 23212, chi2cdf = 1.0
idx = 23213, chi2cdf = 1.0
idx = 23214, chi2cdf = 0.9999999997460371
idx = 23215, chi2cdf = 1.0
idx = 23216, chi2cdf = 1.0
idx = 23217, chi2cdf = 0.9999999997460371
idx = 23218, chi2cdf = 1.0
idx = 23219, chi2cdf = 1.0
idx = 23220, chi2cdf = 0.9999999997460371
idx = 23221, chi2cdf = 1.0
idx = 23222, chi2cdf = 1.0
idx = 23223, chi2cdf = 0.9999999997460371
idx = 23224, chi2cdf = 1.0
idx = 23225, chi2cdf = 1.0
idx = 23226, chi2cdf = 0.9999999997460371
idx = 23227, chi2cdf = 1.0
idx = 23228, chi2cdf = 1.0
idx = 23229, chi2cdf = 0.9999999997460371
idx = 23230, chi2cdf = 1.0
idx = 23231, chi2cdf = 1.0
idx = 23232, chi2cdf = 1.0
idx = 23233, chi2cdf = 1.0
idx = 23234, chi2cdf = 1.0
idx = 23235, chi2cdf = 1.0
idx = 23236, chi2cdf = 1.0
idx = 23237, chi2cdf = 1.0
idx = 23238, chi2cdf = 1.0
idx = 23239, chi2cdf = 1.0
idx = 23240, chi2cdf = 1.0
idx = 23241, chi2cdf = 1.0
idx = 23242, chi2cdf = 1.0
idx = 23243, chi2cdf = 1.0
idx = 23244, chi2cdf = 1.0
idx = 23245, chi2cdf = 1.0
idx = 23246, chi2cdf = 1.0
idx = 23247, chi2cdf = 1.0
idx = 23248, chi2cdf = 1.0
idx = 23249, chi2cdf = 1.0
idx = 23250, chi2cdf = 1.0
idx = 23251, chi2cdf = 1.0
idx = 23252, chi2cdf = 1.0
idx = 23253, chi2cdf = 1.0
idx = 23254, chi2cdf = 1.0
idx = 23255, chi2cdf = 1.0
idx = 23256, chi2cdf = 1.0
idx = 23257, chi2cdf = 1.0
idx = 23258, chi2cdf = 1.0
idx = 23259, chi2cdf = 1.0
idx = 23260, chi2cdf = 1.0
idx = 23261, chi2cdf = 1.0
idx = 23262, chi2cdf = 1.0
idx = 23263, chi2cdf = 1.0
idx = 23264, chi2cdf = 1.0
idx = 23265, chi2cdf = 1.0
idx = 23266, chi2cdf = 1.0
idx = 23267, chi2cdf = 1.0
idx = 23269, chi2cdf = 1.0
idx = 23271, chi2cdf = 1.0
idx = 23273, chi2cdf = 1.0
idx = 23275, chi2cdf = 1.0
idx = 23276, chi2cdf = 1.0
idx = 23277, chi2cdf = 1.0
idx = 23278, chi2cdf = 1.0
idx = 23279, chi2cdf = 1.0
idx = 23280, chi2cdf = 1.0
idx = 23281, chi2cdf = 1.0
idx = 23282, chi2cdf = 1.0
idx = 23283, chi2cdf = 1.0
idx = 23284, chi2cdf = 1.0
idx = 23285, chi2cdf = 1.0
idx = 23286, chi2cdf = 1.0
idx = 23287, chi2cdf = 1.0
idx = 23288, chi2cdf = 1.0
idx = 23289, chi2cdf = 1.0
idx = 23290, chi2cdf = 1.0
idx = 23291, chi2cdf = 1.0
idx = 23292, chi2cdf = 1.0
idx = 23293, chi2cdf = 1.0
idx = 23294, chi2cdf = 1.0
idx = 23295, chi2cdf = 1.0
idx = 23296, chi2cdf = 1.0
idx = 23297, chi2cdf = 1.0
idx = 23298, chi2cdf = 1.0
idx = 23299, chi2cdf = 1.0
idx = 23300, chi2cdf = 1.0
idx = 23301, chi2cdf = 1.0
idx = 23302, chi2cdf = 1.0
idx = 23303, chi2cdf = 1.0
idx = 23304, chi2cdf = 1.0
idx = 23305, chi2cdf = 1.0
idx = 23306, chi2cdf = 1.0
idx = 23307, chi2cdf = 1.0
idx = 23308, chi2cdf = 1.0
idx = 23309, chi2cdf = 1.0
idx = 23310, chi2cdf = 1.0
idx = 23311, chi2cdf = 1.0
idx = 23312, chi2cdf = 1.0
idx = 23313, chi2cdf = 1.0
idx = 23314, chi2cdf = 1.0
idx = 23315, chi2cdf = 1.0
idx = 23316, chi2cdf = 1.0
idx = 23317, chi2cdf = 1.0
idx = 23318, chi2cdf = 1.0
idx = 23319, chi2cdf = 1.0
idx = 23320, chi2cdf = 1.0
idx = 23321, chi2cdf = 1.0
idx = 23322, chi2cdf = 1.0
idx = 23323, chi2cdf = 1.0
idx = 23324, chi2cdf = 1.0
idx = 23325, chi2cdf = 1.0
idx = 23326, chi2cdf = 1.0
idx = 23327, chi2cdf = 1.0
idx = 23328, chi2cdf = 1.0
idx = 23329, chi2cdf = 1.0
idx = 23330, chi2cdf = 1.0
idx = 23333, chi2cdf = 1.0
idx = 23334, chi2cdf = 1.0
idx = 23335, chi2cdf = 1.0
idx = 23338, chi2cdf = 1.0
idx = 23339, chi2cdf = 1.0
idx = 23340, chi2cdf = 1.0
idx = 23343, chi2cdf = 1.0
idx = 23344, chi2cdf = 1.0
idx = 23345, chi2cdf = 1.0
idx = 23348, chi2cdf = 1.0
idx = 23349, chi2cdf = 1.0
idx = 23350, chi2cdf = 1.0
idx = 23351, chi2cdf = 1.0
idx = 23352, chi2cdf = 1.0
idx = 23353, chi2cdf = 1.0
idx = 23354, chi2cdf = 1.0
idx = 23355, chi2cdf = 1.0
idx = 23356, chi2cdf = 1.0
idx = 23357, chi2cdf = 1.0
idx = 23358, chi2cdf = 1.0
idx = 23359, chi2cdf = 1.0
idx = 23360, chi2cdf = 1.0
idx = 23361, chi2cdf = 1.0
idx = 23362, chi2cdf = 1.0
idx = 23363, chi2cdf = 1.0
idx = 23364, chi2cdf = 1.0
idx = 23365, chi2cdf = 1.0
idx = 23366, chi2cdf = 1.0
idx = 23367, chi2cdf = 1.0
idx = 23368, chi2cdf = 1.0
idx = 23369, chi2cdf = 1.0
idx = 23370, chi2cdf = 1.0
idx = 23371, chi2cdf = 1.0
idx = 23372, chi2cdf = 1.0
idx = 23373, chi2cdf = 1.0
idx = 23374, chi2cdf = 1.0
idx = 23375, chi2cdf = 1.0
idx = 23380, chi2cdf = 1.0
idx = 23381, chi2cdf = 1.0
idx = 23382, chi2cdf = 1.0
idx = 23383, chi2cdf = 1.0
idx = 23384, chi2cdf = 1.0
idx = 23385, chi2cdf = 1.0
idx = 23386, chi2cdf = 1.0
idx = 23387, chi2cdf = 1.0
idx = 23388, chi2cdf = 1.0
idx = 23389, chi2cdf = 1.0
idx = 23390, chi2cdf = 1.0
idx = 23391, chi2cdf = 1.0
idx = 23392, chi2cdf = 1.0
idx = 23393, chi2cdf = 1.0
idx = 23394, chi2cdf = 1.0
idx = 23395, chi2cdf = 1.0
idx = 23396, chi2cdf = 1.0
idx = 23397, chi2cdf = 1.0
idx = 23398, chi2cdf = 1.0
idx = 23399, chi2cdf = 1.0
idx = 23400, chi2cdf = 1.0
idx = 23401, chi2cdf = 1.0
idx = 23402, chi2cdf = 1.0
idx = 23403, chi2cdf = 1.0
idx = 23404, chi2cdf = 1.0
idx = 23405, chi2cdf = 1.0
idx = 23406, chi2cdf = 1.0
idx = 23407, chi2cdf = 1.0
idx = 23408, chi2cdf = 1.0
idx = 23409, chi2cdf = 1.0
idx = 23410, chi2cdf = 1.0
idx = 23411, chi2cdf = 1.0
idx = 23412, chi2cdf = 1.0
idx = 23413, chi2cdf = 1.0
idx = 23414, chi2cdf = 1.0
idx = 23415, chi2cdf = 1.0
idx = 23416, chi2cdf = 1.0
idx = 23417, chi2cdf = 1.0
idx = 23418, chi2cdf = 1.0
idx = 23419, chi2cdf = 1.0
idx = 23420, chi2cdf = 1.0
idx = 23421, chi2cdf = 1.0
idx = 23422, chi2cdf = 1.0
idx = 23423, chi2cdf = 1.0
idx = 23424, chi2cdf = 1.0
idx = 23425, chi2cdf = 1.0
idx = 23426, chi2cdf = 1.0
idx = 23427, chi2cdf = 1.0
idx = 23428, chi2cdf = 1.0
idx = 23429, chi2cdf = 1.0
idx = 23432, chi2cdf = 1.0
idx = 23433, chi2cdf = 1.0
idx = 23434, chi2cdf = 1.0
idx = 23435, chi2cdf = 1.0
idx = 23438, chi2cdf = 1.0
idx = 23439, chi2cdf = 1.0
idx = 23440, chi2cdf = 1.0
idx = 23441, chi2cdf = 1.0
idx = 23444, chi2cdf = 1.0
idx = 23445, chi2cdf = 1.0
idx = 23446, chi2cdf = 1.0
idx = 23447, chi2cdf = 1.0
idx = 23450, chi2cdf = 1.0
idx = 23451, chi2cdf = 1.0
idx = 23452, chi2cdf = 1.0
idx = 23453, chi2cdf = 1.0
idx = 23454, chi2cdf = 1.0
idx = 23455, chi2cdf = 1.0
idx = 23456, chi2cdf = 1.0
idx = 23457, chi2cdf = 1.0
idx = 23458, chi2cdf = 1.0
idx = 23459, chi2cdf = 1.0
idx = 23460, chi2cdf = 1.0
idx = 23461, chi2cdf = 1.0
idx = 23462, chi2cdf = 1.0
idx = 23463, chi2cdf = 1.0
idx = 23464, chi2cdf = 1.0
idx = 23465, chi2cdf = 1.0
idx = 23466, chi2cdf = 1.0
idx = 23467, chi2cdf = 1.0
idx = 23468, chi2cdf = 1.0
idx = 23469, chi2cdf = 1.0
idx = 23470, chi2cdf = 1.0
idx = 23471, chi2cdf = 1.0
idx = 23472, chi2cdf = 1.0
idx = 23473, chi2cdf = 1.0
idx = 23474, chi2cdf = 1.0
idx = 23475, chi2cdf = 1.0
idx = 23476, chi2cdf = 1.0
idx = 23477, chi2cdf = 1.0
idx = 23478, chi2cdf = 1.0
idx = 23479, chi2cdf = 1.0
idx = 23480, chi2cdf = 1.0
idx = 23481, chi2cdf = 1.0
idx = 23482, chi2cdf = 1.0
idx = 23483, chi2cdf = 1.0
idx = 23488, chi2cdf = 1.0
idx = 23489, chi2cdf = 1.0
idx = 23490, chi2cdf = 1.0
idx = 23491, chi2cdf = 1.0
idx = 23492, chi2cdf = 1.0
idx = 23497, chi2cdf = 1.0
idx = 23498, chi2cdf = 1.0
idx = 23499, chi2cdf = 1.0
idx = 23500, chi2cdf = 1.0
idx = 23501, chi2cdf = 1.0
idx = 23502, chi2cdf = 1.0
idx = 23503, chi2cdf = 1.0
idx = 23504, chi2cdf = 1.0
idx = 23505, chi2cdf = 1.0
idx = 23506, chi2cdf = 1.0
idx = 23507, chi2cdf = 1.0
idx = 23508, chi2cdf = 1.0
idx = 23509, chi2cdf = 1.0
idx = 23510, chi2cdf = 1.0
idx = 23511, chi2cdf = 1.0
idx = 23512, chi2cdf = 1.0
idx = 23513, chi2cdf = 1.0
idx = 23514, chi2cdf = 1.0
idx = 23515, chi2cdf = 1.0
idx = 23516, chi2cdf = 1.0
idx = 23517, chi2cdf = 1.0
idx = 23518, chi2cdf = 1.0
idx = 23519, chi2cdf = 1.0
idx = 23520, chi2cdf = 1.0
idx = 23521, chi2cdf = 1.0
idx = 23522, chi2cdf = 1.0
idx = 23523, chi2cdf = 1.0
idx = 23524, chi2cdf = 1.0
idx = 23525, chi2cdf = 1.0
idx = 23526, chi2cdf = 1.0
idx = 23527, chi2cdf = 1.0
idx = 23528, chi2cdf = 1.0
idx = 23529, chi2cdf = 1.0
idx = 23530, chi2cdf = 1.0
idx = 23531, chi2cdf = 1.0
idx = 23532, chi2cdf = 1.0
idx = 23533, chi2cdf = 1.0
idx = 23534, chi2cdf = 1.0
idx = 23535, chi2cdf = 1.0
idx = 23536, chi2cdf = 1.0
idx = 23537, chi2cdf = 1.0
idx = 23538, chi2cdf = 1.0
idx = 23539, chi2cdf = 1.0
idx = 23540, chi2cdf = 1.0
idx = 23541, chi2cdf = 1.0
idx = 23542, chi2cdf = 1.0
idx = 23543, chi2cdf = 1.0
idx = 23544, chi2cdf = 1.0
idx = 23545, chi2cdf = 1.0
idx = 23546, chi2cdf = 1.0
idx = 23547, chi2cdf = 1.0
idx = 23548, chi2cdf = 1.0
idx = 23549, chi2cdf = 1.0
idx = 23550, chi2cdf = 1.0
idx = 23551, chi2cdf = 1.0
idx = 23552, chi2cdf = 1.0
idx = 23553, chi2cdf = 1.0
idx = 23554, chi2cdf = 1.0
idx = 23555, chi2cdf = 1.0
idx = 23557, chi2cdf = 1.0
idx = 23558, chi2cdf = 1.0
idx = 23559, chi2cdf = 1.0
idx = 23560, chi2cdf = 1.0
idx = 23561, chi2cdf = 1.0
idx = 23563, chi2cdf = 1.0
idx = 23564, chi2cdf = 1.0
idx = 23565, chi2cdf = 1.0
idx = 23566, chi2cdf = 1.0
idx = 23567, chi2cdf = 1.0
idx = 23569, chi2cdf = 1.0
idx = 23570, chi2cdf = 1.0
idx = 23571, chi2cdf = 1.0
idx = 23572, chi2cdf = 1.0
idx = 23573, chi2cdf = 1.0
idx = 23575, chi2cdf = 1.0
idx = 23576, chi2cdf = 1.0
idx = 23577, chi2cdf = 1.0
idx = 23578, chi2cdf = 1.0
idx = 23579, chi2cdf = 1.0
idx = 23580, chi2cdf = 1.0
idx = 23581, chi2cdf = 1.0
idx = 23582, chi2cdf = 1.0
idx = 23583, chi2cdf = 1.0
idx = 23584, chi2cdf = 1.0
idx = 23585, chi2cdf = 1.0
idx = 23586, chi2cdf = 1.0
idx = 23587, chi2cdf = 1.0
idx = 23588, chi2cdf = 1.0
idx = 23589, chi2cdf = 1.0
idx = 23590, chi2cdf = 1.0
idx = 23591, chi2cdf = 1.0
idx = 23592, chi2cdf = 1.0
idx = 23593, chi2cdf = 1.0
idx = 23594, chi2cdf = 1.0
idx = 23595, chi2cdf = 1.0
idx = 23596, chi2cdf = 1.0
idx = 23597, chi2cdf = 1.0
idx = 23598, chi2cdf = 1.0
idx = 23599, chi2cdf = 1.0
idx = 23600, chi2cdf = 1.0
idx = 23601, chi2cdf = 1.0
idx = 23602, chi2cdf = 1.0
idx = 23603, chi2cdf = 1.0
idx = 23604, chi2cdf = 1.0
idx = 23605, chi2cdf = 1.0
idx = 23606, chi2cdf = 1.0
idx = 23607, chi2cdf = 1.0
idx = 23608, chi2cdf = 1.0
idx = 23609, chi2cdf = 1.0
idx = 23626, chi2cdf = 1.0
idx = 23627, chi2cdf = 1.0
idx = 23628, chi2cdf = 1.0
idx = 23629, chi2cdf = 1.0
idx = 23630, chi2cdf = 1.0
idx = 23631, chi2cdf = 1.0
idx = 23632, chi2cdf = 1.0
idx = 23633, chi2cdf = 1.0
idx = 23634, chi2cdf = 1.0
idx = 23635, chi2cdf = 1.0
idx = 23636, chi2cdf = 1.0
idx = 23637, chi2cdf = 1.0
idx = 23638, chi2cdf = 1.0
idx = 23639, chi2cdf = 1.0
idx = 23640, chi2cdf = 1.0
idx = 23641, chi2cdf = 1.0
idx = 23642, chi2cdf = 1.0
idx = 23643, chi2cdf = 1.0
idx = 23644, chi2cdf = 1.0
idx = 23645, chi2cdf = 1.0
idx = 23646, chi2cdf = 1.0
idx = 23647, chi2cdf = 1.0
idx = 23648, chi2cdf = 1.0
idx = 23649, chi2cdf = 1.0
idx = 23650, chi2cdf = 1.0
idx = 23651, chi2cdf = 1.0
idx = 23652, chi2cdf = 1.0
idx = 23653, chi2cdf = 1.0
idx = 23654, chi2cdf = 1.0
idx = 23655, chi2cdf = 1.0
idx = 23656, chi2cdf = 1.0
idx = 23657, chi2cdf = 1.0
idx = 23658, chi2cdf = 1.0
idx = 23659, chi2cdf = 1.0
idx = 23660, chi2cdf = 1.0
idx = 23661, chi2cdf = 1.0
idx = 23662, chi2cdf = 1.0
idx = 23663, chi2cdf = 1.0
idx = 23664, chi2cdf = 1.0
idx = 23665, chi2cdf = 1.0
idx = 23666, chi2cdf = 1.0
idx = 23667, chi2cdf = 1.0
idx = 23668, chi2cdf = 1.0
idx = 23669, chi2cdf = 1.0
idx = 23670, chi2cdf = 1.0
idx = 23671, chi2cdf = 1.0
idx = 23672, chi2cdf = 1.0
idx = 23673, chi2cdf = 1.0
idx = 23674, chi2cdf = 1.0
idx = 23675, chi2cdf = 1.0
idx = 23676, chi2cdf = 1.0
idx = 23677, chi2cdf = 1.0
idx = 23678, chi2cdf = 1.0
idx = 23679, chi2cdf = 1.0
idx = 23680, chi2cdf = 1.0
idx = 23681, chi2cdf = 1.0
idx = 23682, chi2cdf = 1.0
idx = 23683, chi2cdf = 1.0
idx = 23684, chi2cdf = 1.0
idx = 23685, chi2cdf = 1.0
idx = 23686, chi2cdf = 1.0
idx = 23687, chi2cdf = 1.0
idx = 23688, chi2cdf = 1.0
idx = 23689, chi2cdf = 1.0
idx = 23690, chi2cdf = 1.0
idx = 23691, chi2cdf = 1.0
idx = 23692, chi2cdf = 1.0
idx = 23693, chi2cdf = 1.0
idx = 23694, chi2cdf = 1.0
idx = 23695, chi2cdf = 1.0
idx = 23696, chi2cdf = 1.0
idx = 23697, chi2cdf = 1.0
idx = 23698, chi2cdf = 1.0
idx = 23699, chi2cdf = 1.0
idx = 23704, chi2cdf = 1.0
idx = 23705, chi2cdf = 1.0
idx = 23706, chi2cdf = 1.0
idx = 23707, chi2cdf = 1.0
idx = 23708, chi2cdf = 1.0
idx = 23709, chi2cdf = 1.0
idx = 23710, chi2cdf = 1.0
idx = 23711, chi2cdf = 1.0
idx = 23712, chi2cdf = 1.0
idx = 23713, chi2cdf = 1.0
idx = 23714, chi2cdf = 1.0
idx = 23715, chi2cdf = 1.0
idx = 23716, chi2cdf = 1.0
idx = 23717, chi2cdf = 1.0
idx = 23718, chi2cdf = 1.0
idx = 23719, chi2cdf = 1.0
idx = 23720, chi2cdf = 1.0
idx = 23721, chi2cdf = 1.0
idx = 23722, chi2cdf = 1.0
idx = 23723, chi2cdf = 1.0
idx = 23724, chi2cdf = 1.0
idx = 23725, chi2cdf = 1.0
idx = 23726, chi2cdf = 1.0
idx = 23727, chi2cdf = 1.0
idx = 23728, chi2cdf = 1.0
idx = 23729, chi2cdf = 1.0
idx = 23730, chi2cdf = 1.0
idx = 23731, chi2cdf = 1.0
idx = 23732, chi2cdf = 1.0
idx = 23733, chi2cdf = 1.0
idx = 23734, chi2cdf = 1.0
idx = 23735, chi2cdf = 1.0
idx = 23736, chi2cdf = 1.0
idx = 23737, chi2cdf = 1.0
idx = 23738, chi2cdf = 1.0
idx = 23739, chi2cdf = 1.0
idx = 23740, chi2cdf = 1.0
idx = 23741, chi2cdf = 1.0
idx = 23742, chi2cdf = 1.0
idx = 23743, chi2cdf = 1.0
idx = 23744, chi2cdf = 1.0
idx = 23745, chi2cdf = 1.0
idx = 23746, chi2cdf = 1.0
idx = 23747, chi2cdf = 1.0
idx = 23748, chi2cdf = 1.0
idx = 23749, chi2cdf = 1.0
idx = 23750, chi2cdf = 1.0
idx = 23751, chi2cdf = 1.0
idx = 23752, chi2cdf = 1.0
idx = 23753, chi2cdf = 1.0
idx = 23758, chi2cdf = 1.0
idx = 23764, chi2cdf = 1.0
idx = 23770, chi2cdf = 1.0
idx = 23776, chi2cdf = 1.0
idx = 23778, chi2cdf = 1.0
idx = 23779, chi2cdf = 1.0
idx = 23780, chi2cdf = 1.0
idx = 23781, chi2cdf = 1.0
idx = 23782, chi2cdf = 1.0
idx = 23783, chi2cdf = 1.0
idx = 23784, chi2cdf = 1.0
idx = 23785, chi2cdf = 1.0
idx = 23786, chi2cdf = 1.0
idx = 23787, chi2cdf = 1.0
idx = 23788, chi2cdf = 1.0
idx = 23789, chi2cdf = 1.0
idx = 23790, chi2cdf = 1.0
idx = 23791, chi2cdf = 1.0
idx = 23792, chi2cdf = 1.0
idx = 23793, chi2cdf = 1.0
idx = 23794, chi2cdf = 1.0
idx = 23795, chi2cdf = 1.0
idx = 23796, chi2cdf = 1.0
idx = 23797, chi2cdf = 1.0
idx = 23798, chi2cdf = 1.0
idx = 23799, chi2cdf = 1.0
idx = 23800, chi2cdf = 1.0
idx = 23801, chi2cdf = 1.0
idx = 23802, chi2cdf = 1.0
idx = 23803, chi2cdf = 1.0
idx = 23804, chi2cdf = 1.0
idx = 23805, chi2cdf = 1.0
idx = 23806, chi2cdf = 1.0
idx = 23807, chi2cdf = 1.0
idx = 23808, chi2cdf = 1.0
idx = 23809, chi2cdf = 1.0
idx = 23810, chi2cdf = 1.0
idx = 23811, chi2cdf = 1.0
idx = 23812, chi2cdf = 1.0
idx = 23813, chi2cdf = 1.0
idx = 23814, chi2cdf = 1.0
idx = 23815, chi2cdf = 1.0
idx = 23816, chi2cdf = 1.0
idx = 23817, chi2cdf = 1.0
idx = 23818, chi2cdf = 1.0
idx = 23819, chi2cdf = 1.0
idx = 23820, chi2cdf = 1.0
idx = 23821, chi2cdf = 1.0
idx = 23822, chi2cdf = 1.0
idx = 23823, chi2cdf = 1.0
idx = 23824, chi2cdf = 1.0
idx = 23825, chi2cdf = 1.0
idx = 23826, chi2cdf = 1.0
idx = 23827, chi2cdf = 1.0
idx = 23828, chi2cdf = 1.0
idx = 23829, chi2cdf = 1.0
idx = 23830, chi2cdf = 1.0
idx = 23831, chi2cdf = 1.0
idx = 23832, chi2cdf = 1.0
idx = 23833, chi2cdf = 1.0
idx = 23834, chi2cdf = 1.0
idx = 23835, chi2cdf = 1.0
idx = 23836, chi2cdf = 1.0
idx = 23837, chi2cdf = 1.0
idx = 23838, chi2cdf = 1.0
idx = 23839, chi2cdf = 1.0
idx = 23840, chi2cdf = 1.0
idx = 23841, chi2cdf = 1.0
idx = 23842, chi2cdf = 1.0
idx = 23843, chi2cdf = 1.0
idx = 23844, chi2cdf = 1.0
idx = 23845, chi2cdf = 1.0
idx = 23846, chi2cdf = 1.0
idx = 23847, chi2cdf = 1.0
idx = 23848, chi2cdf = 1.0
idx = 23849, chi2cdf = 1.0
idx = 23850, chi2cdf = 1.0
idx = 23851, chi2cdf = 1.0
idx = 23852, chi2cdf = 1.0
idx = 23853, chi2cdf = 1.0
idx = 23854, chi2cdf = 1.0
idx = 23855, chi2cdf = 1.0
idx = 23856, chi2cdf = 1.0
idx = 23857, chi2cdf = 1.0
idx = 23858, chi2cdf = 1.0
idx = 23859, chi2cdf = 1.0
idx = 23860, chi2cdf = 1.0
idx = 23861, chi2cdf = 1.0
idx = 23866, chi2cdf = 1.0
idx = 23867, chi2cdf = 1.0
idx = 23868, chi2cdf = 1.0
idx = 23869, chi2cdf = 1.0
idx = 23870, chi2cdf = 1.0
idx = 23871, chi2cdf = 1.0
idx = 23872, chi2cdf = 1.0
idx = 23873, chi2cdf = 1.0
idx = 23874, chi2cdf = 1.0
idx = 23875, chi2cdf = 1.0
idx = 23876, chi2cdf = 1.0
idx = 23877, chi2cdf = 1.0
idx = 23878, chi2cdf = 1.0
idx = 23879, chi2cdf = 1.0
idx = 23880, chi2cdf = 1.0
idx = 23881, chi2cdf = 1.0
idx = 23882, chi2cdf = 1.0
idx = 23883, chi2cdf = 1.0
idx = 23884, chi2cdf = 1.0
idx = 23885, chi2cdf = 1.0
idx = 23886, chi2cdf = 1.0
idx = 23887, chi2cdf = 1.0
idx = 23888, chi2cdf = 1.0
idx = 23889, chi2cdf = 1.0
idx = 23890, chi2cdf = 1.0
idx = 23891, chi2cdf = 1.0
idx = 23892, chi2cdf = 1.0
idx = 23893, chi2cdf = 1.0
idx = 23894, chi2cdf = 1.0
idx = 23895, chi2cdf = 1.0
idx = 23896, chi2cdf = 1.0
idx = 23897, chi2cdf = 1.0
idx = 23898, chi2cdf = 1.0
idx = 23899, chi2cdf = 1.0
idx = 23900, chi2cdf = 1.0
idx = 23901, chi2cdf = 1.0
idx = 23902, chi2cdf = 1.0
idx = 23903, chi2cdf = 1.0
idx = 23904, chi2cdf = 1.0
idx = 23905, chi2cdf = 1.0
idx = 23906, chi2cdf = 1.0
idx = 23907, chi2cdf = 1.0
idx = 23908, chi2cdf = 1.0
idx = 23909, chi2cdf = 1.0
idx = 23910, chi2cdf = 1.0
idx = 23911, chi2cdf = 1.0
idx = 23912, chi2cdf = 1.0
idx = 23913, chi2cdf = 1.0
idx = 23914, chi2cdf = 1.0
idx = 23915, chi2cdf = 1.0
idx = 23916, chi2cdf = 1.0
idx = 23917, chi2cdf = 1.0
idx = 23918, chi2cdf = 1.0
idx = 23919, chi2cdf = 1.0
idx = 23920, chi2cdf = 1.0
idx = 23921, chi2cdf = 1.0
idx = 23922, chi2cdf = 1.0
idx = 23923, chi2cdf = 1.0
idx = 23924, chi2cdf = 1.0
idx = 23927, chi2cdf = 1.0
idx = 23928, chi2cdf = 1.0
idx = 23931, chi2cdf = 1.0
idx = 23932, chi2cdf = 1.0
idx = 23935, chi2cdf = 1.0
idx = 23936, chi2cdf = 1.0
idx = 23939, chi2cdf = 1.0
idx = 23940, chi2cdf = 1.0
idx = 23941, chi2cdf = 1.0
idx = 23942, chi2cdf = 1.0
idx = 23943, chi2cdf = 1.0
idx = 23944, chi2cdf = 1.0
idx = 23945, chi2cdf = 1.0
idx = 23946, chi2cdf = 1.0
idx = 23947, chi2cdf = 1.0
idx = 23948, chi2cdf = 1.0
idx = 23949, chi2cdf = 1.0
idx = 23950, chi2cdf = 1.0
idx = 23951, chi2cdf = 1.0
idx = 23952, chi2cdf = 1.0
idx = 23953, chi2cdf = 1.0
idx = 23954, chi2cdf = 1.0
idx = 23955, chi2cdf = 1.0
idx = 23956, chi2cdf = 1.0
idx = 23957, chi2cdf = 1.0
idx = 23958, chi2cdf = 1.0
idx = 23959, chi2cdf = 1.0
idx = 23960, chi2cdf = 1.0
idx = 23961, chi2cdf = 1.0
idx = 23962, chi2cdf = 1.0
idx = 23963, chi2cdf = 1.0
idx = 23964, chi2cdf = 1.0
idx = 23965, chi2cdf = 1.0
idx = 23974, chi2cdf = 1.0
idx = 23975, chi2cdf = 1.0
idx = 23976, chi2cdf = 1.0
idx = 23977, chi2cdf = 1.0
idx = 23978, chi2cdf = 1.0
idx = 23979, chi2cdf = 1.0
idx = 23980, chi2cdf = 1.0
idx = 23981, chi2cdf = 1.0
idx = 23982, chi2cdf = 1.0
idx = 23983, chi2cdf = 1.0
idx = 23984, chi2cdf = 1.0
idx = 23985, chi2cdf = 1.0
idx = 23986, chi2cdf = 1.0
idx = 23987, chi2cdf = 1.0
idx = 23988, chi2cdf = 1.0
idx = 23989, chi2cdf = 1.0
idx = 23990, chi2cdf = 1.0
idx = 23991, chi2cdf = 1.0
idx = 23992, chi2cdf = 1.0
idx = 23993, chi2cdf = 1.0
idx = 23994, chi2cdf = 1.0
idx = 23995, chi2cdf = 1.0
idx = 23996, chi2cdf = 1.0
idx = 23997, chi2cdf = 1.0
idx = 23998, chi2cdf = 1.0
idx = 23999, chi2cdf = 1.0
idx = 24000, chi2cdf = 1.0
idx = 24001, chi2cdf = 1.0
idx = 24002, chi2cdf = 1.0
idx = 24003, chi2cdf = 1.0
idx = 24004, chi2cdf = 1.0
idx = 24005, chi2cdf = 1.0
idx = 24006, chi2cdf = 1.0
idx = 24007, chi2cdf = 1.0
idx = 24008, chi2cdf = 1.0
idx = 24009, chi2cdf = 1.0
idx = 24010, chi2cdf = 1.0
idx = 24011, chi2cdf = 1.0
idx = 24012, chi2cdf = 1.0
idx = 24013, chi2cdf = 1.0
idx = 24014, chi2cdf = 1.0
idx = 24015, chi2cdf = 1.0
idx = 24016, chi2cdf = 1.0
idx = 24017, chi2cdf = 1.0
idx = 24018, chi2cdf = 1.0
idx = 24019, chi2cdf = 1.0
idx = 24020, chi2cdf = 1.0
idx = 24021, chi2cdf = 1.0
idx = 24022, chi2cdf = 1.0
idx = 24023, chi2cdf = 1.0
idx = 24024, chi2cdf = 1.0
idx = 24025, chi2cdf = 1.0
idx = 24026, chi2cdf = 1.0
idx = 24027, chi2cdf = 1.0
idx = 24028, chi2cdf = 1.0
idx = 24029, chi2cdf = 1.0

,hash,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
8511,01701bf8635b2095,0,16,False,True,8,2,2,25600,256,0,1,25600,2598596,1.000000,True
8564,708a5474d5bf9cf8,0,16,True,False,8,2,2,25600,256,0,1,25600,2598596,1.000000,True
8572,1f839344d1585d48,0,16,True,False,9,2,2,25600,512,0,1,25600,1314528,1.000000,True
17821,0d45f80a53c46f18,0,16,True,True,3,4,4,6400000,64,0,1,6400000,640013193954,0.999999,True
23205,058cad01a53ca801,0,8,False,False,1,2,0,40,2,0,1,40,1600,1.000000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37926,699568eaf77c0227,0,0,True,True,6,30,0,72900000000,729000000,0,1,72900000000,1747706771649134592,1.000000,True
37935,1a40f73191b1b194,0,0,True,True,3,200,0,80000000000,8000000,0,1,80000000000,17426550496495140864,1.000000,True
37946,0c65aef169d703b1,0,0,True,True,4,200,0,80000000000,1600000000,0,1,80000000000,17426550496495140864,1.000000,True
37952,78dd53d98f1bcf8a,0,0,True,True,4,30,0,81000000000,810000,0,1,81000000000,12405853833109176320,1.000000,True
37973,44eb9a12378d04f5,0,0,True,True,1,8388608,0,83886080000,8388608,0,1,83886080000,8664925683060834304,1.000000,True